# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geosite.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeosite.proto\"\xe1\x01\n\x06\x44omain\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.Domain.Type\x12\r\n\x05value\x18\x02 \x01(\t\x12$\n\tattribute\x18\x03 \x03(\x0b\x32\x11.Domain.Attribute\x1aR\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x42\r\n\x0btyped_value\"2\n\x04Type\x12\t\n\x05Plain\x10\x00\x12\t\n\x05Regex\x10\x01\x12\n\n\x06\x44omain\x10\x02\x12\x08\n\x04\x46ull\x10\x03\"1\n\tSiteGroup\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x17\n\x06\x64omain\x18\x02 \x03(\x0b\x32\x07.Domain\"/\n\rSiteGroupList\x12\x1e\n\nsite_group\x18\x01 \x03(\x0b\x32\n.SiteGroupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geosite_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOMAIN']._serialized_start=18
  _globals['_DOMAIN']._serialized_end=243
  _globals['_DOMAIN_ATTRIBUTE']._serialized_start=109
  _globals['_DOMAIN_ATTRIBUTE']._serialized_end=191
  _globals['_DOMAIN_TYPE']._serialized_start=193
  _globals['_DOMAIN_TYPE']._serialized_end=243
  _globals['_SITEGROUP']._serialized_start=245
  _globals['_SITEGROUP']._serialized_end=294
  _globals['_SITEGROUPLIST']._serialized_start=296
  _globals['_SITEGROUPLIST']._serialized_end=343
# @@protoc_insertion_point(module_scope)
